apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: carbon-relay
spec:
  replicas: 10
  template:
    metadata:
      labels:
        component: graphite
        app: carbon-relay
    spec:
      containers:
        - name: carbon-relay
          image: alexmdoc/carbon-relay
          ports:
          - containerPort: 2003
            name: plaintext
            protocol: TCP
          - containerPort: 2004
            name: pickle
            protocol: TCP
      serviceAccountName: graphite-cluster-sa
