apiVersion: v1
kind: Service
metadata:
  name: carbon-relay
  labels:
     role: proxy
     cluster: statsd
spec:
  type: LoadBalancer
  selector:
    app: carbon-relay
  ports:
  - port: 2003
    name: plaintext
    targetPort: 2003
    protocol: TCP
  - port: 2004
    name: pickle
    targetPort: 2004
    protocol: TCP
