apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graphite
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: graphite
        app: graphite
    spec:
      containers:
        - name: graphite
          image: mdemri/graphite-master
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 4096Mi
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /opt/graphite/conf
      serviceAccountName: graphite-cluster-sa
      volumes:
        - name: config-volume
          configMap:
            name: graphite-config
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: graphite
  labels:
    app: graphite
    component: graphite
spec:
  type: ClusterIP
  selector:
    app: graphite
  ports:
  - port: 80
    name: http
    protocol: TCP
