apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoints-reader
subjects:
- kind: ServiceAccount
  name: graphite-cluster-sa
