apiVersion: v1
kind: Service
metadata:
  name: graphite
  labels:
    app: graphite
    component: graphite
spec:
  type: ClusterIP
  selector:
    app: graphite
  ports:
  - port: 80
    name: http
    protocol: TCP
